name: Build Magisk module

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: Setup Android NDK
      working-directory: ./magic_overlayfs
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip android-ndk-r23b-linux.zip
    - name: Move build script
      run: | 
        cp ./build.sh magic_overlayfs/build.sh
    - name: Build
      working-directory: ./magic_overlayfs
      id: build
      run: |
        chmod 777 ./build.sh
        ./build.sh
    - name: Upload release
      uses: actions/upload-artifact@v3
      with:
        name: magisk-overlayfs_and_adb-root-enabler_release
        path: magic_overlayfs/out/magisk-module
